### ISSUE TITLE
epic: s42 deployment across campus (clusters maps)

### ISSUE THREAD

**Issue by 42Atomys** [42Atomys/stud42#309]
### Please exprime yourself

This epic regroups all the active campuses of 42 network. Our goal is to provide service to all campuses. 

### Europe

- [ ] [Austria] Vienna
- [ ] [Belgium] Brussels
- [ ] [Czech Republic] Prague
- [ ] [Finland] Helsinki
- [ ] [France] Angouleme
- [ ] [France] Le Havre
- [ ] [France] Lyon
- [ ] [France] Mulhouse
- [ ] [France] Nice
- [ ] [France] Paris
- [ ] [France] Perpignan
- [ ] [Germany] Berlin
- [ ] [Germany] Heilbronn
- [ ] [Germany] Wolfsburg
- [ ] [Italy] Florence
- [ ] [Italy] Rome
- [ ] [Luxembourg] Luxembourg
- [ ] [Netherlands] Amsterdam
- [ ] [Portugal] Lisboa
- [ ] [Portugal] Porto
- [ ] [Russian Federation] Kazan
- [ ] [Russian Federation] Moscow
- [ ] [Spain] Alicante
- [ ] [Spain] Barcelona
- [ ] [Spain] Madrid
- [ ] [Spain] Malaga
- [ ] [Spain] Urduliz
- [ ] [Switzerland] Lausanne
- [ ] [Turkey] Istanbul
- [ ] [Turkey] Kocaeli
- [ ] [United Kingdom] London

### America

- [ ] [Brazil] Belo Horizonte
- [ ] [Brazil] Rio de Janeiro
- [ ] [Brazil] São-Paulo
- [ ] [Canada] Quebec

### Asia

- [ ] [Armenia] Yerevan
- [ ] [Japan] Tokyo
- [ ] [Jordan] Amman
- [ ] [Korea, Republic of] Seoul
- [ ] [Malaysia] Kuala Lumpur
- [ ] [Thailand] Bangkok
- [ ] [United Arab Emirates] Abu Dhabi

### Africa

- [ ] [Morocco] Benguerir
- [ ] [Morocco] Khouribga
- [ ] [Morocco] Tétouan

### Oceania

- [ ] [Australia] Adelaide

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
