### ISSUE TITLE
feat: Discord bot to sync role between Github and Discord server

### ISSUE THREAD

**Issue by 42atomys** [42Atomys/stud42#58]
**Is your feature request related to a problem? Please describe.**

Create a Bot Discord with an Oauth2 strategy to check if the person is a sponsor or not. In case the person has linked his Github account to Discord and he is a sponsor, we make him join the discord (so we don't generate an invitation link).

**App**
- [x] #66
- [x] #67
- [x] #69
- [x] #68

**Optimizations/Need Dev Env**
- [x] #175
- [x] #173

**Discord Bot**
- [ ] Bot will set roles of User when he join the server according to its rank on github and its sponsorship level.
- [ ] Bot will accept a Slash command `/roles refresh` to update the roles with the current state (for the User executing the command)
- [ ] Bot sync the version number on the sidebar
- [ ] Bot publish realease note on `#release` channel
- [ ] Bot can be used by user with `STAFF` flag to perform action like: add user to the beta

**Notes**
- Github Sponsors distributes sponsor-related webhooks ( [Webhook Sponsors](https://docs.github.com/en/sponsors/integrating-with-github-sponsors/configuring-webhooks-for-events-in-your-sponsored-account) - [Sponsors Payload References](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#sponsorship) )
