### ISSUE TITLE
misc: migration of the infrastructure to 42 network

### ISSUE THREAD

**Issue by 42atomys** [42atomys/stud42#651]
### Please exprime yourself

The S42 application will be migrated to the 42 Network infrastructure to enhance data protection and reduce costs. This migration is a collaborative effort to provide a new hosting environment for S42.

While the infrastructure and hosting will move to the 42 Network, the application's code, development, and management will remain open-source and community-driven. Only the hosting environment will change.

## TODO
- [ ] update CI
- [ ] update deploy code
- [ ] update the privacy policy
- [ ] update the monitoring

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Message sent on discord : https://discordapp.com/channels/248936708379246593/954502614593192016/1326267869683519654
